# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7a1448400783bfdc651fbbbcc1e5cbb4b750edacf7715181f4ccfc4dc18672d20060383e7824535747871b7080a243c1eb6f11519d337f7ef36649df1852eb4

test:
  secret_key_base: d8c8e708080bb58dda2ef769652f2c2561442010fea7ab6ec66313b081baf0ba1fc272b7059481ec76083f8cfee34e52cbc79a7424390130be3bacd3a7a68fbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
